### ISSUE TITLE
Delete Pairing

### ISSUE THREAD

**Issue by ndrbn0** [ndrbn0/Flavion#43]
## Value proposition

As a user,
I want to delete an existing pairing,
So that I can remove outdated or incorrect pairings from the system.

## Description

![Image](https://github.com/user-attachments/assets/6f33d7c4-b343-4e41-96a0-5f432ec47a01)

## Acceptance criteria
- [ ] The user must be able to see a "Delete" option for each pairing on the pairing-card.
- [ ] Upon clicking the "Delete" option, the system should prompt the user with a confirmation message, asking if they are sure they want to delete the pairing.
- [ ] If the user confirms the deletion, the pairing should be removed from the list and the system.
- [ ] A success message should be displayed to the user indicating the pairing has been successfully deleted. Disappears after 3 seconds.
- [ ] If the user cancels the deletion, the pairing should remain in the list and the system, with no changes made.
## Tasks
- [ ] Add a Delete-Button on the pairing-card
- [ ] Add a Pop-up with the message "Are you sure you want to delete this pairing?"
- [ ] Add a "Yes"- and a "No"-Button to this Pop-up
- [ ] Add a confirmation message that disappears after 3 seconds
- [ ] Add the Delete-Function 
- [ ] Add local storage
