### ISSUE TITLE
Edit Pairing

### ISSUE THREAD

**Issue by ndrbn0** [ndrbn0/Flavion#44]
## Value proposition
As a user,
I want to edit an existing pairing,
So that I can update the information or correct any mistakes in the pairing details.
## Description

![Image](https://github.com/user-attachments/assets/eabe7931-72a8-4cde-877b-12e8c623d242)

## Acceptance criteria
- [ ] The user must be able to see an "Edit" option for each pairing on the pairing card
- [ ] Upon clicking the "Edit" option, the system should present an editable form pre-populated with the current details of the pairing.
- [ ] The form should validate the input fields according to the rules set for each field (e.g., required fields, data formats).
- [ ]  The user must have the ability to save changes after editing the pairing details.
- [ ]  Upon saving, the system should update the pairing with the new details and display a success message.
- [ ]  The user must have the option to cancel the edit process, which will discard any changes and return the user to the pairing list view without saving.

## Tasks
- [ ] Add Edit-Button to each Pairing-Card
- [ ] Add a Form with Inputs as a pop-up
- [ ] Add a Save-Button to the Form
- [ ] Add a Cancel-Button to the Form
- [ ] Add Local Storage to this
